### ISSUE TITLE
double exception thrown when trying to extract collections

### ISSUE THREAD

**Issue by jmtd** [dbeley/bandcamp-library-scraper#1]
This looks very promising. I want a structured data of my collection so I can xref what I have donwloaded. So I follow the instructions

 * visited https://bandcamp.com/jondowland (logged in), scrolled right down until the whole lot is visible, saved it. Resulting file is 1.3M in size and searching it shows data for items right at the bottom of my collection, so it looks like it loaded in ok. Then:

```
$ python bandcamp-library-scraper.py -f library-2023-02-18.html -t collection
Traceback (most recent call last):
  File "/home/jon/git/bandcamp-library-scraper/bandcamp-library-scraper.py", line 89, in extract_collection
    .text.strip()
     ^^^^
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/git/bandcamp-library-scraper/bandcamp-library-scraper.py", line 282, in <module>
    main()
  File "/home/jon/git/bandcamp-library-scraper/bandcamp-library-scraper.py", line 239, in main
    list_albums = extract_collection(soup)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jon/git/bandcamp-library-scraper/bandcamp-library-scraper.py", line 94, in extract_collection
    f"Couldn't extract number of collections for album {album_name}."
                                                        ^^^^^^^^^^
NameError: name 'album_name' is not defined. Did you mean: 'album_infos'?
```

**Comment by dbeley** [comment]
Hey sorry about that there was a small issue with a warning log, it should be fixed now :slightly_smiling_face:
